version: "3"
services:
  springboot-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: admin
      MYSQL_PASSWORD: rootroot
      MYSQL_DB: product
    depends_on:
      - mysqldb
    networks:
      - springboot_mysql_net

  mysqldb :
    container_name: mysqldb
    image: mysql:8.1.0
    volumes:
      - ./db3:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: rootroot
      MYSQL_DATABASE: product
      MYSQL_ROOT_PASSWORD: root
    networks:
      - springboot_mysql_net

networks:
  springboot_mysql_net:
    driver: bridge