name : Deploy Jar to AWS S3
on :
  push:
    branches:
      - main
jobs :
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Grant execute permission for gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Copy Jar
        run: cp ./build/libs/sol-coupang-0.0.1-SNAPSHOT.jar ./app.jar

      - name: Zip Files
        run: zip -r deploy.zip ./app.jar ./scripts/* ./appspec.yml

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Upload Jar Compose to S3
        run: |
          aws s3 cp deploy.zip s3://sol-codedeploy-demo/deploy.zip
